### ISSUE TITLE
A license for your project?

### ISSUE THREAD

**Issue by UntidyRAM** [MathewMorrow/STM32-SD-Logging-DMA#1]
Hi,

I like what you have done with the code used to read and write to an SD card. I think lots of people will find it helpful! Unfortunately the community can't use any of it unless you have an open source license 😛 

Verbatim copy from [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license):
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. 

Cheers,
Nick

**Comment by MathewMorrow** [comment]
Added MIT license. Thanks.

**Comment by MathewMorrow** [comment]
Closed.
